<?php

/**
 * @file
 * One-off script to build the support_tickets View, then export.
 * Run: ddev drush php:script scripts/build_support_tickets_view.php
 */

use Drupal\views\Entity\View;

$existing = View::load('support_tickets');
if ($existing) {
  $existing->delete();
}

$field_defaults = [
  'plugin_id' => 'field',
  'entity_type' => 'support_ticket',
  'group_type' => 'group',
  'multi_type' => 'separator',
  'separator' => ', ',
  'field_api_classes' => FALSE,
  'element_type' => '',
  'element_class' => '',
  'element_label_type' => '',
  'element_label_class' => '',
  'element_label_colon' => TRUE,
  'element_wrapper_type' => '',
  'element_wrapper_class' => '',
  'element_default_classes' => TRUE,
  'empty' => '',
  'hide_empty' => FALSE,
  'empty_zero' => FALSE,
  'hide_alter_empty' => TRUE,
  'click_sort_column' => 'value',
  'type' => 'string',
  'settings' => [],
  'group_column' => 'value',
  'group_columns' => [],
  'group_rows' => TRUE,
  'delta_limit' => 0,
  'delta_offset' => 0,
  'delta_reversed' => FALSE,
  'delta_first_last' => FALSE,
];

$view = View::create([
  'id' => 'support_tickets',
  'label' => 'Support tickets',
  'module' => 'views',
  'base_table' => 'support_ticket',
  'base_field' => 'id',
  'description' => 'List and filter support tickets.',
  'tag' => 'support_tickets',
  'core' => '10.x',
  'display' => [
    'default' => [
      'id' => 'default',
      'display_title' => 'Default',
      'display_plugin' => 'default',
      'position' => 0,
      'display_options' => [
        'title' => 'Support tickets',
        'access' => [
          'type' => 'perm',
          'options' => ['perm' => 'access support tickets'],
        ],
        'cache' => ['type' => 'tag', 'options' => []],
        'query' => [
          'type' => 'views_query',
          'options' => [
            'query_comment' => '',
            'disable_sql_rewrite' => FALSE,
            'distinct' => FALSE,
            'replica' => FALSE,
            'query_tags' => [],
          ],
        ],
        'exposed_form' => [
          'type' => 'basic',
          'options' => [
            'submit_button' => 'Filter',
            'reset_button' => TRUE,
            'reset_button_label' => 'Reset',
            'exposed_sorts_label' => 'Sort by',
            'expose_sort_order' => TRUE,
            'sort_asc_label' => 'Asc',
            'sort_desc_label' => 'Desc',
          ],
        ],
        'pager' => [
          'type' => 'mini',
          'options' => [
            'offset' => 0,
            'pagination_heading_level' => 'h4',
            'items_per_page' => 25,
            'total_pages' => NULL,
            'id' => 0,
            'tags' => ['next' => '››', 'previous' => '‹‹'],
            'expose' => [
              'items_per_page' => FALSE,
              'items_per_page_label' => 'Items per page',
              'items_per_page_options' => '5, 10, 25, 50',
              'items_per_page_options_all' => FALSE,
              'items_per_page_options_all_label' => '- All -',
              'offset' => FALSE,
              'offset_label' => 'Offset',
            ],
          ],
        ],
        'style' => [
          'type' => 'table',
          'options' => [
            'grouping' => [],
            'row_class' => 'support-tickets-table__row',
            'default_row_class' => TRUE,
            'columns' => [
              'title' => 'title',
              'status' => 'status',
              'priority' => 'priority',
              'assigned_to' => 'assigned_to',
              'changed' => 'changed',
              'edit_support_ticket' => 'edit_support_ticket',
            ],
            'default' => 'changed',
            'info' => [
              'title' => [
                'sortable' => TRUE,
                'default_sort_order' => 'asc',
                'align' => '',
                'separator' => '',
                'empty_column' => FALSE,
                'responsive' => '',
              ],
              'status' => [
                'sortable' => TRUE,
                'default_sort_order' => 'asc',
                'align' => '',
                'separator' => '',
                'empty_column' => FALSE,
                'responsive' => '',
              ],
              'priority' => [
                'sortable' => TRUE,
                'default_sort_order' => 'asc',
                'align' => '',
                'separator' => '',
                'empty_column' => FALSE,
                'responsive' => '',
              ],
              'assigned_to' => [
                'sortable' => FALSE,
                'default_sort_order' => 'asc',
                'align' => '',
                'separator' => '',
                'empty_column' => FALSE,
                'responsive' => 'priority-low',
              ],
              'changed' => [
                'sortable' => TRUE,
                'default_sort_order' => 'desc',
                'align' => '',
                'separator' => '',
                'empty_column' => FALSE,
                'responsive' => 'priority-medium',
              ],
              'edit_support_ticket' => [
                'sortable' => FALSE,
                'default_sort_order' => 'asc',
                'align' => '',
                'separator' => '',
                'empty_column' => FALSE,
                'responsive' => '',
              ],
            ],
            'override' => TRUE,
            'sticky' => FALSE,
            'summary' => '',
            'empty_table' => FALSE,
            'caption' => '',
            'description' => '',
            'class' => 'support-tickets-table',
          ],
        ],
        'row' => ['type' => 'fields'],
        'fields' => [
          'title' => $field_defaults + [
            'id' => 'title',
            'table' => 'support_ticket',
            'field' => 'title',
            'relationship' => 'none',
            'group_type' => 'group',
            'admin_label' => '',
            'entity_field' => 'title',
            'label' => 'Title',
            'exclude' => FALSE,
            'alter' => [
              'alter_text' => FALSE,
              'text' => '',
              'make_link' => FALSE,
              'path' => '',
              'absolute' => FALSE,
              'external' => FALSE,
              'replace_spaces' => FALSE,
              'path_case' => 'none',
              'trim_whitespace' => FALSE,
              'alt' => '',
              'rel' => '',
              'link_class' => '',
              'prefix' => '',
              'suffix' => '',
              'target' => '',
              'nl2br' => FALSE,
              'max_length' => 0,
              'word_boundary' => TRUE,
              'ellipsis' => TRUE,
              'more_link' => FALSE,
              'more_link_text' => '',
              'more_link_path' => '',
              'strip_tags' => FALSE,
              'trim' => FALSE,
              'preserve_tags' => '',
              'html' => FALSE,
            ],
            'element_label_colon' => FALSE,
            'click_sort_column' => 'value',
            'type' => 'string',
            'settings' => ['link_to_entity' => TRUE],
          ],
          'status' => $field_defaults + [
            'id' => 'status',
            'table' => 'support_ticket',
            'field' => 'status',
            'relationship' => 'none',
            'admin_label' => '',
            'entity_field' => 'status',
            'label' => 'Status',
            'exclude' => FALSE,
            'alter' => [
              'alter_text' => FALSE,
              'text' => '',
              'make_link' => FALSE,
              'path' => '',
              'absolute' => FALSE,
              'external' => FALSE,
              'replace_spaces' => FALSE,
              'path_case' => 'none',
              'trim_whitespace' => FALSE,
              'alt' => '',
              'rel' => '',
              'link_class' => '',
              'prefix' => '',
              'suffix' => '',
              'target' => '',
              'nl2br' => FALSE,
              'max_length' => 0,
              'word_boundary' => TRUE,
              'ellipsis' => TRUE,
              'more_link' => FALSE,
              'more_link_text' => '',
              'more_link_path' => '',
              'strip_tags' => FALSE,
              'trim' => FALSE,
              'preserve_tags' => '',
              'html' => FALSE,
            ],
            'element_label_colon' => FALSE,
            'click_sort_column' => 'value',
            'type' => 'list_default',
            'settings' => [],
          ],
          'priority' => $field_defaults + [
            'id' => 'priority',
            'table' => 'support_ticket',
            'field' => 'priority',
            'relationship' => 'none',
            'admin_label' => '',
            'entity_field' => 'priority',
            'label' => 'Priority',
            'exclude' => FALSE,
            'alter' => [
              'alter_text' => FALSE,
              'text' => '',
              'make_link' => FALSE,
              'path' => '',
              'absolute' => FALSE,
              'external' => FALSE,
              'replace_spaces' => FALSE,
              'path_case' => 'none',
              'trim_whitespace' => FALSE,
              'alt' => '',
              'rel' => '',
              'link_class' => '',
              'prefix' => '',
              'suffix' => '',
              'target' => '',
              'nl2br' => FALSE,
              'max_length' => 0,
              'word_boundary' => TRUE,
              'ellipsis' => TRUE,
              'more_link' => FALSE,
              'more_link_text' => '',
              'more_link_path' => '',
              'strip_tags' => FALSE,
              'trim' => FALSE,
              'preserve_tags' => '',
              'html' => FALSE,
            ],
            'element_label_colon' => FALSE,
            'click_sort_column' => 'value',
            'type' => 'list_default',
            'settings' => [],
          ],
          'assigned_to' => [
            'id' => 'assigned_to',
            'table' => 'support_ticket',
            'field' => 'assigned_to',
            'relationship' => 'none',
            'group_type' => 'group',
            'admin_label' => '',
            'entity_type' => 'support_ticket',
            'entity_field' => 'assigned_to',
            'plugin_id' => 'field',
            'label' => 'Assignee',
            'exclude' => FALSE,
            'alter' => [
              'alter_text' => FALSE,
              'text' => '',
              'make_link' => FALSE,
              'path' => '',
              'absolute' => FALSE,
              'external' => FALSE,
              'replace_spaces' => FALSE,
              'path_case' => 'none',
              'trim_whitespace' => FALSE,
              'alt' => '',
              'rel' => '',
              'link_class' => '',
              'prefix' => '',
              'suffix' => '',
              'target' => '',
              'nl2br' => FALSE,
              'max_length' => 0,
              'word_boundary' => TRUE,
              'ellipsis' => TRUE,
              'more_link' => FALSE,
              'more_link_text' => '',
              'more_link_path' => '',
              'strip_tags' => FALSE,
              'trim' => FALSE,
              'preserve_tags' => '',
              'html' => FALSE,
            ],
            'element_type' => '',
            'element_class' => '',
            'element_label_type' => '',
            'element_label_class' => '',
            'element_label_colon' => FALSE,
            'element_wrapper_type' => '',
            'element_wrapper_class' => '',
            'element_default_classes' => TRUE,
            'empty' => '—',
            'hide_empty' => FALSE,
            'empty_zero' => FALSE,
            'hide_alter_empty' => TRUE,
            'click_sort_column' => 'target_id',
            'type' => 'entity_reference_label',
            'settings' => ['link' => FALSE],
            'group_column' => 'target_id',
            'group_columns' => [],
            'group_rows' => TRUE,
            'delta_limit' => 0,
            'delta_offset' => 0,
            'delta_reversed' => FALSE,
            'delta_first_last' => FALSE,
            'multi_type' => 'separator',
            'separator' => ', ',
            'field_api_classes' => FALSE,
          ],
          'changed' => [
            'id' => 'changed',
            'table' => 'support_ticket',
            'field' => 'changed',
            'relationship' => 'none',
            'group_type' => 'group',
            'admin_label' => '',
            'entity_type' => 'support_ticket',
            'entity_field' => 'changed',
            'plugin_id' => 'field',
            'label' => 'Updated',
            'exclude' => FALSE,
            'alter' => [
              'alter_text' => FALSE,
              'text' => '',
              'make_link' => FALSE,
              'path' => '',
              'absolute' => FALSE,
              'external' => FALSE,
              'replace_spaces' => FALSE,
              'path_case' => 'none',
              'trim_whitespace' => FALSE,
              'alt' => '',
              'rel' => '',
              'link_class' => '',
              'prefix' => '',
              'suffix' => '',
              'target' => '',
              'nl2br' => FALSE,
              'max_length' => 0,
              'word_boundary' => TRUE,
              'ellipsis' => TRUE,
              'more_link' => FALSE,
              'more_link_text' => '',
              'more_link_path' => '',
              'strip_tags' => FALSE,
              'trim' => FALSE,
              'preserve_tags' => '',
              'html' => FALSE,
            ],
            'element_type' => '',
            'element_class' => '',
            'element_label_type' => '',
            'element_label_class' => '',
            'element_label_colon' => FALSE,
            'element_wrapper_type' => '',
            'element_wrapper_class' => '',
            'element_default_classes' => TRUE,
            'empty' => '',
            'hide_empty' => FALSE,
            'empty_zero' => FALSE,
            'hide_alter_empty' => TRUE,
            'click_sort_column' => 'value',
            'type' => 'timestamp',
            'settings' => [
              'date_format' => 'medium',
              'custom_date_format' => '',
              'timezone' => '',
              'tooltip' => ['date_format' => '', 'custom_date_format' => ''],
              'time_diff' => [
                'enabled' => FALSE,
                'future_format' => '@interval hence',
                'past_format' => '@interval ago',
                'granularity' => 2,
                'refresh' => 60,
              ],
            ],
            'group_column' => 'value',
            'group_columns' => [],
            'group_rows' => TRUE,
            'delta_limit' => 0,
            'delta_offset' => 0,
            'delta_reversed' => FALSE,
            'delta_first_last' => FALSE,
            'multi_type' => 'separator',
            'separator' => ', ',
            'field_api_classes' => FALSE,
          ],
          'edit_support_ticket' => [
            'id' => 'edit_support_ticket',
            'table' => 'support_ticket',
            'field' => 'edit_support_ticket',
            'relationship' => 'none',
            'group_type' => 'group',
            'admin_label' => '',
            'entity_type' => 'support_ticket',
            'plugin_id' => 'entity_link_edit',
            'label' => '',
            'exclude' => FALSE,
            'alter' => [
              'alter_text' => FALSE,
              'text' => '',
              'make_link' => FALSE,
              'path' => '',
              'absolute' => FALSE,
              'external' => FALSE,
              'replace_spaces' => FALSE,
              'path_case' => 'none',
              'trim_whitespace' => FALSE,
              'alt' => '',
              'rel' => '',
              'link_class' => 'support-tickets-table__edit',
              'prefix' => '',
              'suffix' => '',
              'target' => '',
              'nl2br' => FALSE,
              'max_length' => 0,
              'word_boundary' => TRUE,
              'ellipsis' => TRUE,
              'more_link' => FALSE,
              'more_link_text' => '',
              'more_link_path' => '',
              'strip_tags' => FALSE,
              'trim' => FALSE,
              'preserve_tags' => '',
              'html' => FALSE,
            ],
            'element_type' => '',
            'element_class' => '',
            'element_label_type' => '',
            'element_label_class' => '',
            'element_label_colon' => FALSE,
            'element_wrapper_type' => '',
            'element_wrapper_class' => '',
            'element_default_classes' => TRUE,
            'empty' => '',
            'hide_empty' => FALSE,
            'empty_zero' => FALSE,
            'hide_alter_empty' => TRUE,
            'text' => 'Edit',
            'output_url_as_text' => FALSE,
            'absolute' => FALSE,
          ],
        ],
        'filters' => [
          'status' => [
            'id' => 'status',
            'table' => 'support_ticket',
            'field' => 'status',
            'relationship' => 'none',
            'group_type' => 'group',
            'admin_label' => '',
            'entity_type' => 'support_ticket',
            'entity_field' => 'status',
            'plugin_id' => 'list_field',
            'operator' => 'or',
            'value' => [],
            'group' => 1,
            'exposed' => TRUE,
            'expose' => [
              'operator_id' => 'status_op',
              'label' => 'Status',
              'description' => '',
              'use_operator' => FALSE,
              'operator' => 'status_op',
              'operator_limit_selection' => FALSE,
              'operator_list' => [],
              'identifier' => 'status',
              'required' => FALSE,
              'remember' => FALSE,
              'multiple' => FALSE,
              'remember_roles' => ['authenticated' => 'authenticated'],
              'reduce' => FALSE,
            ],
            'is_grouped' => FALSE,
            'group_info' => [
              'label' => '',
              'description' => '',
              'identifier' => '',
              'optional' => TRUE,
              'widget' => 'select',
              'multiple' => FALSE,
              'remember' => FALSE,
              'default_group' => 'All',
              'default_group_multiple' => [],
              'group_items' => [],
            ],
            'reduce_duplicates' => FALSE,
          ],
          'combine' => [
            'id' => 'combine',
            'table' => 'views',
            'field' => 'combine',
            'relationship' => 'none',
            'group_type' => 'group',
            'admin_label' => '',
            'plugin_id' => 'combine',
            'operator' => 'contains',
            'value' => '',
            'group' => 1,
            'exposed' => TRUE,
            'expose' => [
              'operator_id' => 'combine_op',
              'label' => 'Search',
              'description' => 'Search title and description',
              'use_operator' => FALSE,
              'operator' => 'combine_op',
              'operator_limit_selection' => FALSE,
              'operator_list' => [],
              'identifier' => 'search',
              'required' => FALSE,
              'remember' => FALSE,
              'multiple' => FALSE,
              'remember_roles' => ['authenticated' => 'authenticated'],
              'placeholder' => 'Keyword…',
            ],
            'fields' => [
              'title' => 'title',
              'description' => 'description',
            ],
          ],
        ],
        'filter_groups' => [
          'operator' => 'AND',
          'groups' => [1 => 'AND'],
        ],
        'sorts' => [
          'changed' => [
            'id' => 'changed',
            'table' => 'support_ticket',
            'field' => 'changed',
            'relationship' => 'none',
            'group_type' => 'group',
            'admin_label' => '',
            'entity_type' => 'support_ticket',
            'entity_field' => 'changed',
            'plugin_id' => 'date',
            'order' => 'DESC',
            'expose' => [
              'label' => '',
              'field_identifier' => '',
            ],
            'exposed' => FALSE,
            'granularity' => 'second',
          ],
        ],
        'header' => [],
        'footer' => [],
        'empty' => [
          'area_text_custom' => [
            'id' => 'area_text_custom',
            'table' => 'views',
            'field' => 'area_text_custom',
            'relationship' => 'none',
            'group_type' => 'group',
            'admin_label' => '',
            'plugin_id' => 'text_custom',
            'empty' => TRUE,
            'content' => 'No tickets match your search.',
            'tokenize_spaces' => 0,
          ],
        ],
        'relationships' => [],
        'arguments' => [],
        'display_extenders' => [],
        'css_class' => 'support-tickets-view',
      ],
      'cache_metadata' => [
        'max-age' => -1,
        'contexts' => [
          'languages:language_content',
          'languages:language_interface',
          'url',
          'url.query_args',
          'user.permissions',
        ],
        'tags' => [],
      ],
    ],
    'page_list' => [
      'id' => 'page_list',
      'display_title' => 'Page',
      'display_plugin' => 'page',
      'position' => 1,
      'display_options' => [
        'display_extenders' => [],
        'path' => 'support-tickets',
        'menu' => [
          'type' => 'normal',
          'title' => 'Support tickets',
          'description' => 'Browse and filter support tickets',
          'weight' => 0,
          'expanded' => FALSE,
          'menu_name' => 'main',
          'parent' => '',
          'context' => '0',
        ],
      ],
      'cache_metadata' => [
        'max-age' => -1,
        'contexts' => [
          'languages:language_content',
          'languages:language_interface',
          'url',
          'url.query_args',
          'user.permissions',
        ],
        'tags' => [],
      ],
    ],
  ],
]);

// Combine filter needs description as a views field too for combine to work.
// Add description as excluded field.
$displays = $view->get('display');
$desc = $displays['default']['display_options']['fields']['title'];
$desc['id'] = 'description';
$desc['field'] = 'description';
$desc['entity_field'] = 'description';
$desc['label'] = 'Description';
$desc['exclude'] = TRUE;
$desc['settings'] = [];
$desc['type'] = 'basic_string';
$displays['default']['display_options']['fields']['description'] = $desc;
// Reorder: put description after title in fields array by rebuilding.
$fields = $displays['default']['display_options']['fields'];
$ordered = [
  'title' => $fields['title'],
  'description' => $fields['description'],
  'status' => $fields['status'],
  'priority' => $fields['priority'],
  'assigned_to' => $fields['assigned_to'],
  'changed' => $fields['changed'],
  'edit_support_ticket' => $fields['edit_support_ticket'],
];
$displays['default']['display_options']['fields'] = $ordered;
$view->set('display', $displays);
$view->save();

echo "View saved: support_tickets\n";
